### ISSUE TITLE
输入我的邀请码 J9R4JV 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

### ISSUE THREAD

**Issue by vincentou114** [ntkernel/lantern#13]
输入我的邀请码 J9R4JV 来获得三个月的蓝灯专业版！立即下载 https://github.com/getlantern/forum

**Comment by ntkernel** [comment]
怎么弄？？下载个研究研究？或者你可以发个安装包吗，电脑手机都可以，最好都发，谢谢。
