### ISSUE TITLE
这里的解压安装程序是什么意思？是安装4.4后的文件位置里面的打开程序吗？

### ISSUE THREAD

**Issue by byzzxc** [ntkernel/lantern#18]

**Comment by ntkernel** [comment]
把安装包后缀exe改成zip，解压。
现在都用ss了，蓝灯已经用不了了。

**Comment by byzzxc** [comment]
好的，谢谢




------------------ 原始邮件 ------------------
发件人: "LLT"<notifications@github.com>; 
发送时间: 2019年7月15日(星期一) 中午11:34
收件人: "ntkernel/lantern"<lantern@noreply.github.com>; 
抄送: "扬帆起航"<985754226@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [ntkernel/lantern] 这里的解压安装程序是什么意思？是安装4.4后的文件位置里面的打开程序吗？ (#18)




把安装包后缀exe改成zip，解压。
 现在都用ss了，蓝灯已经用不了了。
