### ISSUE TITLE
请问ss还有更新吗，全军覆没了呀~

### ISSUE THREAD

**Issue by Plauncher12138** [ntkernel/lantern#24]

**Comment by logTXT** [comment]
全军覆没+1

**Comment by ntkernel** [comment]
有的，我现在忙，我这两天之内更新


---原始邮件---
发件人: &quot;唐新天&quot;<notifications@github.com&gt;
发送时间: 2019年9月19日(星期四) 晚上7:11
收件人: &quot;ntkernel/lantern&quot;<lantern@noreply.github.com&gt;;
抄送: &quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题: Re: [ntkernel/lantern] 请问ss还有更新吗，全军覆没了呀~ (#24)



全军覆没+1
 
&mdash;

**Comment by ntkernel** [comment]
这周线路炸了，我下周更新，希望可以等待

**Comment by ljphawk** [comment]
> 这周线路炸了，我下周更新，希望可以等待

谢谢大佬

**Comment by a364176773** [comment]
> 这周线路炸了，我下周更新，希望可以等待

感谢大佬

**Comment by a364176773** [comment]
> 这周线路炸了，我下周更新，希望可以等待

大佬,啥时候更新呀,@ntkernel 感谢感谢

**Comment by onlybemyself** [comment]
自己在vultr上建的好几个都同时挂了，，，国家加大力度了？

**Comment by ntkernel** [comment]
国庆没办法，我也没得用，来源是旋风加速器，大家去找找，https://www.xf8.im/，如果什么时候能用了，告诉我，我会及时提取给大家，大概就是从/data/data/com.network.xfjsq/no_backup/shadowsocks.conf这个文件里面提取的，root的了就可以自己提取，我不知道付费行不行，有钱的可以试试付费，成功了就尽量分享给大家吧，不行也不要怪我，毕竟我没有试过

**Comment by ntkernel** [comment]
有一个ovpn
