### ISSUE TITLE
关于vmess的问题

### ISSUE THREAD

**Issue by JinMinghan18** [ntkernel/lantern#27]
我安卓上用bifrost显示url不支持是怎么回事

**Comment by ntkernel** [comment]
用v2rayNG
https://alitest.vcxv.cc:8443/vng.apk

**Comment by ntkernel** [comment]
这个链接不是长期有效，心情不好就没了，建议去 https://github.com/2dust/v2rayNG 的release下载，只不过国内可能访问不了release。
