### ISSUE TITLE
为什么Vmess里面的连不上啊？

### ISSUE THREAD

**Issue by LiaoBaogan** [ntkernel/lantern#29]
read tcp [2001:250:3002:4252:e569:2c39:dc5c:1fa1]:62178->[2606:4700:30::6812:3dd1]:80: i/o timeout] > v2ray.com/core/common/retry: all retry attempts failed

**Comment by ntkernel** [comment]
可以的，我在阿里云测试过

**Comment by ntkernel** [comment]
![捕获](https://user-images.githubusercontent.com/29348451/66702329-20293100-ed39-11e9-9ab8-c9b9f54750ae.PNG)

**Comment by a364176773** [comment]
@ntkernel 文件里倒数3个配置连上正常,但是无法访问谷歌,我换我公司的配置是可以的
