### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by majinding** [ntkernel/lantern#3]
![image](https://user-images.githubusercontent.com/2681645/51578804-cdcd8900-1ef9-11e9-8b00-b7dcf2f16bca.png)

**Comment by ntkernel** [comment]
试多几次，我这边一直都可以，如果还不行，去  https://github.com/JuncoJet/unlimited-landeng-for-win  这里问吧，可能有些地方的网络封锁了蓝灯。
