### ISSUE TITLE
大佬，这个vmess配置要怎么搞呀，端口要写多少……

### ISSUE THREAD

**Issue by GannonSun** [ntkernel/lantern#32]
vmess://ew0KICAidiI6ICIyIiwNCiAgInBzIjogIlNHIMK3wrfCt8K3wrfCt8K3wrfCt8K3wrfCt8K3djB4MC4xIzI4NyIsDQogICJhZGQiOiAiczI4Ny53ZXdhbGwudG9wIiwNCiAgInBvcnQiOiAiODAiLA0KICAiaWQiOiAiZWUwN2U3ZmItODQ4MC00NmVlLTk0MGUtN2JhMDlkNjQ3MjQxIiwNCiAgImFpZCI6ICIyMzMiLA0KICAibmV0IjogIndzIiwNCiAgInR5cGUiOiAibm9uZSIsDQogICJob3N0IjogIiIsDQogICJwYXRoIjogIiIsDQogICJ0bHMiOiAiIg0KfQ==:8011: too many colons in address] > v2ray.com/core/common/retry: all retry attempts failed
2019/10/14 09:57:30 tcp:127.0.0.1:64162 accepted tcp:clients1.google.com:443

**Comment by JinMinghan18** [comment]
这是URL，直接点app里的＋导入就好了

**Comment by GannonSun** [comment]
> 这是URL，直接点app里的＋介绍就好了

这样子，谢谢啦
