### ISSUE TITLE
100% Data Usage and can not connect.

### ISSUE THREAD

**Issue by YinZho** [ntkernel/lantern#4]
I just download and unzip the file. It works well at the beginning about 0% data usage and connects well. And after about 30min, it looks like this and can not connect.
![image](https://user-images.githubusercontent.com/26624606/52267956-4ceca380-2975-11e9-9911-1f41244dfd0f.png)
Thanks!

**Comment by ntkernel** [comment]
连接不上可能是地区不同，可能你所在的地区蓝灯被禁了。

**Comment by joeguang** [comment]
那这个怎么办呢

**Comment by ntkernel** [comment]
哪个？连不上也没办法，试一下换DNS，可能可以吧，我这几天好像也连不上。

**Comment by WEIFZH** [comment]
@ntkernel 请问您现在解决了这个问题吗？官方版的也是一直连接中，记得三天前还能用。

**Comment by ntkernel** [comment]
我这边手机可以连，电脑坏了，没电脑试，手机4.8.1连不上，4.7.9可以，手机开了之后，端口是8080，电脑改代理到手机应该可以吧。
