### ISSUE TITLE
正版的都用不了了，破解版还能用吗？

### ISSUE THREAD

**Issue by jonenet** [ntkernel/lantern#45]

**Comment by ntkernel** [comment]
用vmess啦，蓝灯没了

**Comment by jonenet** [comment]
能给以vmess的简易配置流程吗，帮画一下整个搭梯子的流程是什么样的

**Comment by ntkernel** [comment]
![help](https://user-images.githubusercontent.com/29348451/75309399-ebeb8280-588b-11ea-81ee-d209ee547cc2.PNG)
直接用好了

**Comment by ntkernel** [comment]
用v2rayN
