### ISSUE TITLE
补丁教程第四步之后LordPE消失

### ISSUE THREAD

**Issue by ChenWeird** [ntkernel/lantern#5]
如题，点导入表右边的两个点之后，lordpe消失。

版本：Bin_LordPE_2010-6-29_3.9_LordPE_1.41_Deluxe_b

**Comment by ntkernel** [comment]
我这个loadpe可以，你试试https://github.com/ntkernel/file/blob/master/LoadPe.7z

**Comment by ChenWeird** [comment]
Thanks！
