### ISSUE TITLE
请问一下，如何添加到订阅？

### ISSUE THREAD

**Issue by tonger67** [ntkernel/lantern#53]
请问一下，如何添加vmess_base64.txt到v2ray的订阅里面？

**Comment by myqlrs** [comment]
打开vmess_base64.txt，把里面的东西复制，然后打开v2ray->服务器->从剪贴板导入批量URL就行了

**Comment by ntkernel** [comment]
把vmess.txt的内容复制，然后剪切板导入

**Comment by ntkernel** [comment]
最近先没时间写自动更新，没必要添加订阅

**Comment by txyyh** [comment]
直接将 https://raw.githubusercontent.com/ntkernel/lantern/master/vmess_base64.txt 添加到订阅中即可，注意需要可以访问此链接。网络条件不好的可以用 jsdelivr cdn：https://cdn.jsdelivr.net/gh/ntkernel/lantern@master/vmess_base64.txt 注意此时效性不太好
