### ISSUE TITLE
cdn 链接显示 你被加入黑名单

### ISSUE THREAD

**Issue by talking-toaster** [ntkernel/lantern#59]
`jsdelivr cdn`
>https://cdn.jsdelivr.net/gh/ntkernel/lantern@master/vmess_base64.txt

`User ntkernel is blacklisted.`

**Comment by tislam8888** [comment]
目测看来这个项目是 被人橄榄了
今天早上四五点的时候 我还正常用着 几个节点
现在试试看 测试 所有节点全部失效

**Comment by fairywings1stbase** [comment]
全部失效+1

**Comment by djfeng** [comment]
全部失效+1

**Comment by DreamUFO** [comment]
cdn节点挂了  希望作者能修复下

**Comment by PeakGymnast** [comment]
全部挂掉了。。。。

**Comment by jackyHuangH** [comment]
作者说明里有写到，这些节点都是从别处提取的，搞不定

**Comment by DreamUFO** [comment]
应该是太久没更新了  更新一波就ok了 
一个多月没更了

**Comment by nathan-code** [comment]
全部失效，大佬有办法吗？谢谢一直以来的分享

**Comment by tislam8888** [comment]
> 全部失效，大佬有办法吗？谢谢一直以来的分享

我看估计有点难了

**Comment by ntkernel** [comment]
我今天之内更。

---原始邮件---
发件人: &quot;tislam8888&quot;<notifications@github.com&gt;
发送时间: 2020年7月24日(星期五) 上午10:58
收件人: &quot;ntkernel/lantern&quot;<lantern@noreply.github.com&gt;;
抄送: &quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题: Re: [ntkernel/lantern] cdn 链接显示 你被加入黑名单 (#59)




  
全部失效，大佬有办法吗？谢谢一直以来的分享
  
我看估计有点难了
 
&mdash;

**Comment by ntkernel** [comment]
下午或者晚上
