### ISSUE TITLE
订阅更新失败

### ISSUE THREAD

**Issue by fairywings1stbase** [ntkernel/lantern#61]
更新订阅开始
2->开始获取订阅内容
2->获取订阅内容成功
2->清除原订阅内容
2->导入订阅内容失败
2->更新订阅结束

**Comment by raeuz** [comment]
+1

**Comment by battlesteed** [comment]
我也是.暂时先手动复制到剪切板吧

**Comment by txyyh** [comment]
jsdelivr 源被加进黑名单了，请用 raw.githubusercontent开头的这个（可能需要外网环境，建议先加个节点拿来获取订阅

**Comment by MuRongPIG** [comment]
这与jsdelivr 源的问题无关 我用raw.githubusercontent这个也不行 看了下是base64编码的那个文件存在问题（和vmess加密后不一样 ）目前只能先直接导入vmess

**Comment by ntkernel** [comment]
好像是的，base64我晚点修，大家先手动导入先，

---原始邮件---
发件人: &quot;MuRongPIG&quot;<notifications@github.com&gt;
发送时间: 2020年7月24日(星期五) 下午5:37
收件人: &quot;ntkernel/lantern&quot;<lantern@noreply.github.com&gt;;
抄送: &quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题: Re: [ntkernel/lantern] 订阅更新失败 (#61)




 
这与jsdelivr 源的问题无关 我用raw.githubusercontent这个也不行 看了下是base64编码的那个文件存在问题（和vmess加密后不一样 ）目前只能先直接导入vmess
 
&mdash;

**Comment by txyyh** [comment]
> 好像是的，base64我晚点修，大家先手动导入先，
> […](#)
> ---原始邮件--- 发件人: &quot;MuRongPIG&quot;<notifications@github.com&gt; 发送时间: 2020年7月24日(星期五) 下午5:37 收件人: &quot;ntkernel/lantern&quot;<lantern@noreply.github.com&gt;; 抄送: &quot;Subscribed&quot;<subscribed@noreply.github.com&gt;; 主题: Re: [ntkernel/lantern] 订阅更新失败 (#61) 这与jsdelivr 源的问题无关 我用raw.githubusercontent这个也不行 看了下是base64编码的那个文件存在问题（和vmess加密后不一样 ）目前只能先直接导入vmess &mdash; You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

我尝试修一下

**Comment by ntkernel** [comment]
已经修复，raw时效不好，等待几分钟
