### ISSUE TITLE
7月24号更新的节点好像全部失效了

### ISSUE THREAD

**Issue by 1912820899** [ntkernel/lantern#66]
希望大佬能更新一下

**Comment by ntkernel** [comment]
晚上更

---原始邮件---
发件人: &quot;李朋泽&quot;<notifications@github.com&gt;
发送时间: 2020年8月8日(星期六) 凌晨0:56
收件人: &quot;ntkernel/lantern&quot;<lantern@noreply.github.com&gt;;
抄送: &quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题: [ntkernel/lantern] 7月24号更新的节点好像全部失效了 (#66)




 
希望大佬能更新一下
 
&mdash;

**Comment by 1912820899** [comment]
多谢





------------------ 原始邮件 ------------------
发件人: LLT <notifications@github.com&gt;
发送时间: 2020年8月8日 12:55
收件人: ntkernel/lantern <lantern@noreply.github.com&gt;
抄送: 李朋泽 <779931346@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[ntkernel/lantern] 7月24号更新的节点好像全部失效了 (#66)





 晚上更 
 
 ---原始邮件--- 
 发件人: &amp;quot;李朋泽&amp;quot;<notifications@github.com&amp;gt; 
 发送时间: 2020年8月8日(星期六) 凌晨0:56 
 收件人: &amp;quot;ntkernel/lantern&amp;quot;<lantern@noreply.github.com&amp;gt;; 
 抄送: &amp;quot;Subscribed&amp;quot;<subscribed@noreply.github.com&amp;gt;; 
 主题: [ntkernel/lantern] 7月24号更新的节点好像全部失效了 (#66) 
 
 
 
 
   
 希望大佬能更新一下 
   
 &amp;mdash;
