### ISSUE TITLE
节点失效了，麻烦更新一下呀

### ISSUE THREAD

**Issue by 1912820899** [ntkernel/lantern#69]

**Comment by canwushuang** [comment]
建议关闭项目。

**Comment by ntkernel** [comment]
这几天内更，要上学。

**Comment by ntkernel** [comment]
这几天内更，要上学。

**Comment by ntkernel** [comment]
这几天内更，要上学。

**Comment by tislam8888** [comment]
然而三天过去了

**Comment by Sanhang88** [comment]
博主想更新就更新，不想更新就不更新，有事情就可以做人家自己的事情，人家做公益还把你们给惯出来了。。。。

**Comment by ntkernel** [comment]
等等啊要上课的。。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ntkernel/lantern"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月15日(星期二) 中午11:03
收件人:&nbsp;"ntkernel/lantern"<lantern@noreply.github.com&gt;;
抄送:&nbsp;"LLT"<1564940789@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [ntkernel/lantern] 节点失效了，麻烦更新一下呀 (#69)





 
博主想更新就更新，不想更新就不更新，有事情就可以做人家自己的事情，人家做公益还把你们给惯出来了。。。。

**Comment by ntkernel** [comment]
更了，cloudflare晚点，
