### ISSUE TITLE
all servers are down?

### ISSUE THREAD

**Issue by SineObama** [ntkernel/lantern#70]
日志如下：

2020/10/25 14:28:58 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)
2020/10/25 14:28:59 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)
2020/10/25 14:29:00 [Warning] failed to handler mux client connection > v2ray.com/core/proxy/vmess/outbound: connection ends > v2ray.com/core/proxy/vmess/outbound: failed to read header > v2ray.com/core/proxy/vmess/encoding: failed to read response header > websocket: close 1000 (normal)

**Comment by strongrex2001** [comment]
+1

**Comment by PeakGymnast** [comment]
**好像节点全挂了。。。。**

**Comment by SineObama** [comment]
刚试了https://t.me/s/V2list上面最新分享的都用不了，奇怪？

**Comment by PeakGymnast** [comment]
> 刚试了https://t.me/s/V2list上面最新分享的都用不了，奇怪？

![`N~O9Q7202]AIRKIH889XU9.png](https://user-images.githubusercontent.com/62637383/97101459-8b416d80-16d8-11eb-8b70-73a51813b28b.png)

我的已经全挂了。。。。

**Comment by jiaobendaye** [comment]
+1

**Comment by 16jdzhang** [comment]
+1 求大大更新

**Comment by tislam8888** [comment]
今天几乎所有的节点都 不能用了
估计是流量爆表了
等待救援

**Comment by ilijiang** [comment]
+1 等待救援

**Comment by battlesteed** [comment]
挂了

**Comment by xiyan-999** [comment]
都挂了

**Comment by ysjsgzq** [comment]
看到你们说都挂了，我就放心了。我还以为是我手机被限流了

**Comment by lon91ong** [comment]
+1

**Comment by LiuWenLibra** [comment]
+1

**Comment by DreamUFO** [comment]
+1

**Comment by lon91ong** [comment]
github都访问不了了，该本机hosts解析到首尔数据中心的ip52.78.231.108才过来的

**Comment by ouyangzn** [comment]
+1

**Comment by zippozeng** [comment]
+1 求大大更新

**Comment by cangkuren** [comment]
+1，我还找了半天原因哈哈哈哈哈

**Comment by FHWWC** [comment]
搭建私人服务器吧，翻车不了。搬瓦工，阿里云等等，也不贵。或者白嫖Azure stu的订阅临时应急

**Comment by cangkuren** [comment]
> 搭建私人服务器吧，翻车不了。搬瓦工，阿里云等等，也不贵。或者白嫖Azure stu的订阅临时应急

如何搭建呀？阿里云可以吗，我怎么听说好像会封

**Comment by PeakGymnast** [comment]
openvpn的都没挂，还能用，你们区[vpngate.net](vpngate.net)这个网站看下，用openvpn连接上面节点信息

**Comment by cangkuren** [comment]
> openvpn的都没挂，还能用，你们区[vpngate.net](https://www.vpngate.net)这个网站看下，用openvpn连接上面节点信息

兄弟，这个怎么连呀，而且看教程，需要密码，但是没找到密码～

**Comment by cangkuren** [comment]
> openvpn的都没挂，还能用，你们区[vpngate.net](https://www.vpngate.net)这个网站看下，用openvpn连接上面节点信息

谢谢，成功了。但是没有订阅的好用，因为所有流量都走vpn，这样用vx什么的都要先把vpn关了

**Comment by FHWWC** [comment]
> > 搭建私人服务器吧，翻车不了。搬瓦工，阿里云等等，也不贵。或者白嫖Azure stu的订阅临时应急
> 
> 如何搭建呀？阿里云可以吗，我怎么听说好像会封

用阿里云国际，别用国内的。
如何搭建网上很多教程，谷歌一下，你就知道。
我是推荐了两个，别的服务商也有好用的。

**Comment by FitzHoo** [comment]
+1

**Comment by lon91ong** [comment]
没人像我一样用[GotoX](https://github.com/SeaHOH/GotoX)临时顶上的吗？
走的CFW，还不清楚有什么限制！

**Comment by lon91ong** [comment]
> > openvpn的都没挂，还能用，你们区[vpngate.net](https://www.vpngate.net)这个网站看下，用openvpn连接上面节点信息
> 
> 谢谢，成功了。但是没有订阅的好用，因为所有流量都走vpn，这样用vx什么的都要先把vpn关了

@cangkuren 路由表应该能解决这个问题！就是折腾费劲

**Comment by tislam8888** [comment]
大佬 不更新了？

**Comment by cangkuren** [comment]
> > > 搭建私人服务器吧，翻车不了。搬瓦工，阿里云等等，也不贵。或者白嫖Azure stu的订阅临时应急
> > 
> > 
> > 如何搭建呀？阿里云可以吗，我怎么听说好像会封
> 
> 用阿里云国际，别用国内的。
> 如何搭建网上很多教程，谷歌一下，你就知道。
> 我是推荐了两个，别的服务商也有好用的。

好像很贵，哈哈哈哈。

**Comment by FHWWC** [comment]
> > > > 搭建私人服务器吧，翻车不了。搬瓦工，阿里云等等，也不贵。或者白嫖Azure stu的订阅临时应急
> > > 
> > > 
> > > 如何搭建呀？阿里云可以吗，我怎么听说好像会封
> > 
> > 
> > 用阿里云国际，别用国内的。
> > 如何搭建网上很多教程，谷歌一下，你就知道。
> > 我是推荐了两个，别的服务商也有好用的。
> 
> 好像很贵，哈哈哈哈。

个人当然买低的了

**Comment by cangkuren** [comment]
> > > > > 搭建私人服务器吧，翻车不了。搬瓦工，阿里云等等，也不贵。或者白嫖Azure stu的订阅临时应急
> > > > 
> > > > 
> > > > 如何搭建呀？阿里云可以吗，我怎么听说好像会封
> > > 
> > > 
> > > 用阿里云国际，别用国内的。
> > > 如何搭建网上很多教程，谷歌一下，你就知道。
> > > 我是推荐了两个，别的服务商也有好用的。
> > 
> > 
> > 好像很贵，哈哈哈哈。
> 
> 个人当然买低的了

你买的多少钱的呀，什么配置

**Comment by cangkuren** [comment]
> 没人像我一样用[GotoX](https://github.com/SeaHOH/GotoX)临时顶上的吗？
> 走的CFW，还不清楚有什么限制！

教程没看懂，就生成了https://XXX.XXX.workers.dev

**Comment by PeakGymnast** [comment]
> 没人像我一样用[GotoX](https://github.com/SeaHOH/GotoX)临时顶上的吗？
> 走的CFW，还不清楚有什么限制！

我。。。。。提示证书不可以，访问不了。。。

**Comment by cangkuren** [comment]
> > 没人像我一样用[GotoX](https://github.com/SeaHOH/GotoX)临时顶上的吗？
> > 走的CFW，还不清楚有什么限制！
> 
> 我。。。。。提示证书不可以，访问不了。。。

不是，我就举个例子，会生成这种结构的一个url地址，然后还需要做什么操作吗

**Comment by cangkuren** [comment]
> openvpn的都没挂，还能用，你们区[vpngate.net](https://www.vpngate.net)这个网站看下，用openvpn连接上面节点信息

换了一个ip，然后就都不行了，晕了。。。

**Comment by cangkuren** [comment]
> openvpn的都没挂，还能用，你们区[vpngate.net](https://www.vpngate.net)这个网站看下，用openvpn连接上面节点信息

是通过把哪个 .ovpn文件下载再来然后导入到openvpn吗？为什么我试了连接不上。。。

**Comment by PeakGymnast** [comment]
> > openvpn的都没挂，还能用，你们区[vpngate.net](https://www.vpngate.net)这个网站看下，用openvpn连接上面节点信息
> 
> 是通过把哪个 .ovpn文件下载再来然后导入到openvpn吗？为什么我试了连接不上。。。

是的，但是，要联有IP的，主机域名的连不上的，tcp通讯协议的最近能连上

**Comment by lon91ong** [comment]
> 
> 教程没看懂，就生成了https://XXX.XXX.workers.dev

生成worker就行了, 修改worker的配置, 修改本地config中的work, 开启本地IPv6管道, 就这些了, 有关勉强能看720p, 好的时候能看1080p

**Comment by cangkuren** [comment]
本地config哪来的...我就是不知道接下来这些步骤😂

**Comment by cangkuren** [comment]
> > 教程没看懂，就生成了https://XXX.XXX.workers.dev
> 
> 生成worker就行了, 修改worker的配置, 修改本地config中的work, 开启本地IPv6管道, 就这些了, 油管勉强能看720p, 好的时候能看1080p

本地config哪来的...我就是不知道接下来这些步骤😂

**Comment by DreamUFO** [comment]
哪个大佬说下vpngate.net速度怎样，几年前用过速度不行啊
gotox备用还行 不能主用啊

**Comment by PeakGymnast** [comment]
> 哪个大佬说下vpngate.net速度怎样，几年前用过速度不行啊
> gotox备用还行 不能主用啊

看运气看脸，有时候很快，openvpn连接vpngate速度还可以

**Comment by FHWWC** [comment]
vmess://eyJhZGQiOiJiYWliZWljYXQudGsiLCJhaWQiOiI2NCIsImhvc3QiOiIiLCJpZCI6IjA1ZjgwYmI2LWJlNDktNDA3ZC04NjJhLTQ4ZGIyMDVlMGE0MCIsIm5ldCI6IndzIiwicGF0aCI6Ii82NTVhMmI3OC8iLCJwb3J0IjoiNDQzIiwicHMiOiJMb3MgQW5nZWxlcyIsInRscyI6InRscyIsInR5cGUiOiJub25lIiwidiI6IjIifQ==

帮忙测试一下速度吧。

> > > > > > 搭建私人服务器吧，翻车不了。搬瓦工，阿里云等等，也不贵。或者白嫖Azure stu的订阅临时应急
> > > > > 
> > > > > 
> > > > > 如何搭建呀？阿里云可以吗，我怎么听说好像会封
> > > > 
> > > > 
> > > > 用阿里云国际，别用国内的。
> > > > 如何搭建网上很多教程，谷歌一下，你就知道。
> > > > 我是推荐了两个，别的服务商也有好用的。
> > > 
> > > 
> > > 好像很贵，哈哈哈哈。
> > 
> > 
> > 个人当然买低的了
> 
> 你买的多少钱的呀，什么配置

https://marketplace.alibabacloud.com/products/56732001/Ubuntu_12_04_32bit-cmjj020513.html?spm=a3c0i.730005-56682004-56732001.0.0.e17f11c5qaJxrE&innerSource=search#pricing

**Comment by FHWWC** [comment]
> > > > > > 搭建私人服务器吧，翻车不了。搬瓦工，阿里云等等，也不贵。或者白嫖Azure stu的订阅临时应急
> > > > > 
> > > > > 
> > > > > 如何搭建呀？阿里云可以吗，我怎么听说好像会封
> > > > 
> > > > 
> > > > 用阿里云国际，别用国内的。
> > > > 如何搭建网上很多教程，谷歌一下，你就知道。
> > > > 我是推荐了两个，别的服务商也有好用的。
> > > 
> > > 
> > > 好像很贵，哈哈哈哈。
> > 
> > 
> > 个人当然买低的了
> 
> 你买的多少钱的呀，什么配置

[here](https://marketplace.alibabacloud.com/products/56732001/Ubuntu_12_04_32bit-cmjj020513.html?spm=a3c0i.730005-56682004-56732001.0.0.e17f11c5qaJxrE&innerSource=search#pricing)

**Comment by tislam8888** [comment]
真的不更新了吗

**Comment by battlesteed** [comment]
估计是不更新了,掏钱买了个,99/年,省心.速度还快

**Comment by cangkuren** [comment]
买的什么...

**Comment by tislam8888** [comment]
看来这个项目是 寿终正寝了

**Comment by Paladinhanxiao** [comment]
我一直好奇这些订阅从哪里破解来的

**Comment by DreamUFO** [comment]
作者 能不能出来给个痛快 到底还维护不

**Comment by Christy-hub** [comment]
应该是不会更新了，最近重新找到个可以用的https://github.com/dodois/dosvpn，虽然速度赶不上付费的，但是白嫖还是香啊

**Comment by Christy-hub** [comment]
> 哪个大佬说下vpngate.net速度怎样，几年前用过速度不行啊
> gotox备用还行 不能主用啊

这两天用了一下dosvpn,感觉速度还行，github.com/dodois/dosvpn

**Comment by cangkuren** [comment]
> 应该是不会更新了，最近重新找到个可以用的https://github.com/dodois/dosvpn 虽然速度赶不上付费的，但是白嫖还是香啊

这个怎么使用呀，是要下载他的软件吗？还是用shadowrocks就行

**Comment by Christy-hub** [comment]
> > 应该是不会更新了，最近重新找到个可以用的https://github.com/dodois/dosvpn 虽然速度赶不上付费的，但是白嫖还是香啊
> 
> 这个怎么使用呀，是要下载他的软件吗？还是用shadowrocks就行

对，要下载软件，直接安装就行了，还可以

**Comment by cangkuren** [comment]
> > > 应该是不会更新了，最近重新找到个可以用的https://github.com/dodois/dosvpn 虽然速度赶不上付费的，但是白嫖还是香啊
> > 
> > 
> > 这个怎么使用呀，是要下载他的软件吗？还是用shadowrocks就行
> 
> 对，要下载软件，直接安装就行了，还可以

有Mac和iOS版本吗

**Comment by DreamUFO** [comment]
dosvpn 这种工具少用 临时救急可以用
主要是 不如ss和v2ray这种 可以自定义 如何使用 
而不是 所有流量都走代理

**Comment by Christy-hub** [comment]
> > > > 应该是不会更新了，最近重新找到个可以用的https://github.com/dodois/dosvpn 虽然速度赶不上付费的，但是白嫖还是香啊
> > > 
> > > 
> > > 这个怎么使用呀，是要下载他的软件吗？还是用shadowrocks就行
> > 
> > 
> > 对，要下载软件，直接安装就行了，还可以
> 
> 有Mac和iOS版本吗

你去看看呢，我用的win版的

**Comment by tislam8888** [comment]
可惜了 这个项目

**Comment by Elijahen** [comment]
> > > > > 应该是不会更新了，最近重新找到个可以用的https://github.com/dodois/dosvpn 虽然速度赶不上付费的，但是白嫖还是香啊
> > > > 
> > > > 
> > > > 这个怎么使用呀，是要下载他的软件吗？还是用shadowrocks就行
> > > 
> > > 
> > > 对，要下载软件，直接安装就行了，还可以
> > 
> > 
> > 有Mac和iOS版本吗
> 
> 你去看看呢，我用的win版的

作者说其它版本还在开发，用了win版的，感觉很稳定啊，美滋滋
