### ISSUE TITLE
hxd链接貌似又全挂了

### ISSUE THREAD

**Issue by SteveXu9102** [ntkernel/lantern#75]
所有连接Tcping平均350ms以内，但是真连接延迟直接报错(正常访问当然是不行的)
![Screenshot_20201107_034551](https://user-images.githubusercontent.com/68725147/98408731-a1720500-20ac-11eb-9204-824e716b1f56.jpg)
![Screenshot_20201107_034608](https://user-images.githubusercontent.com/68725147/98408738-a3d45f00-20ac-11eb-8c1d-112ce3befdba.jpg)

**Comment by tislam8888** [comment]
现在版本的 v2rayn 和 v2rayng 真链接是准确的
我这里是可以用的 目前的节点

![Screenshot_2020-11-08-16-21-28](https://user-images.githubusercontent.com/20881616/98460488-d29f2200-21df-11eb-9042-ec4b4e41136f.png)

![Screenshot_2020-11-08-16-21-40](https://user-images.githubusercontent.com/20881616/98460492-e480c500-21df-11eb-8e92-538987b2d9ca.png)


![Screenshot_2020-11-08-16-22-00](https://user-images.githubusercontent.com/20881616/98460501-037f5700-21e0-11eb-9354-d527408d5f6e.png)

**Comment by SteveXu9102** [comment]
好吧，好像还真不是节点的问题。感谢大兄弟。
