### ISSUE TITLE
请检查Cloudflare Workers链接内容

### ISSUE THREAD

**Issue by SteveXu9102** [ntkernel/lantern#76]
几天前我使用Cloudflare Workers链接更新了订阅，但更新后的节点无法访问(详见ISSUES #75 )；后更换为Github Pages链接更新订阅，节点可访问。Cloudflare Workers链接内容可能有问题，请检查。

**Comment by ntkernel** [comment]
是的，CF那边我没更新，那边更新不方便，可能以后不会更那里了
